on:
  push:
    branches:
      - master
name: deploy to production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: alinz/ssh-scp-action@master
      - run: npm install
      - uses: lannonbr/vsce-action@master
        with:
          key: ${{ secrets.PRODUCTION_SERVER_SSH_KEY }}
          host: kotusiewicz.com
          port: 22
          user: john
          scp: |
            sample1.txt john@example.com:~/sample1.dat
